url: http://localhost:8083
title: gaia
max_order: 2
hips:
  decoder:
    model_path: /home/doserbd/git/Spherinator/gaia/gaia-calibrated-v2/decoder.onnx
    input_name: x
  image_maker:
    class_path: hipster.SpectrumPlotter
    init_args:
      wavelengths:
        start: 336
        stop: 1021
        step: 2
      flip: True
