root_path: HiPSter
html:
  url: http://localhost:8083
  title: HiPSter representation of Gaia XP DR3
  aladin_lite_version: latest
tasks:
  - class_path: hipster.HiPSGenerator
    init_args:
      decoder:
        model_path: /home/doserbd/gaia/gaia-calibrated-v2/decoder.onnx
      image_maker:
        class_path: hipster.SpectrumPlotter
        init_args:
          wavelengths:
            start: 336
            stop: 1021
            step: 2
          figsize_in_pixel: 128
          flip: True
      output_folder: gaia/model_spectrum
      max_order: 1
      hierarchy: 4
  - class_path: hipster.HiPSGenerator
    init_args:
      decoder:
        model_path: /home/doserbd/gaia/gaia-calibrated-v2/decoder.onnx
      image_maker:
        class_path: hipster.AbsorptionLinePlotter
        init_args:
          wavelengths:
            start: 336
            stop: 1021
            step: 2
          figsize_in_pixel: 128
          flip: True
      output_folder: gaia/model_absorption_line
      max_order: 1
      hierarchy: 4
