root_path: HiPSter
html:
  url: http://localhost:8083
  title: HiPSter representation of Gaia XP DR3
  aladin_lite_version: latest
tasks:
  - class_path: hipster.HiPSGenerator
    init_args:
      decoder:
        model_path: decoder.onnx
      image_maker:
        class_path: hipster.SpectrumPlotter
        init_args:
          wavelengths:
            start: 336
            stop: 1021
            step: 2
          ylim: [0, 1]
          margin: 0.02
          figsize_in_pixel: 128
          flip: True
      hips_id: Gaia1
      hips_name: Gaia XP DR3 model spectrum
      hips_path: gaia/model_spectrum
      max_order: 2
      hierarchy: 2
  - class_path: hipster.HiPSGenerator
    init_args:
      decoder:
        model_path: decoder.onnx
      image_maker:
        class_path: hipster.AbsorptionLinePlotter
        init_args:
          wavelengths:
            start: 336
            stop: 1021
            step: 2
          margin: 0.02
          figsize_in_pixel: 128
          flip: True
      hips_id: Gaia2
      hips_name: Gaia XP DR3 model absorption line
      hips_path: gaia/model_absorption_line
      max_order: 2
      hierarchy: 2
